package com.zking.entity;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.title
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.create_time
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.create_by
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.dele_flag
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer deleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.update_time
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.update_by
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.data_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_desc
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private String blogDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.key_words
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private String keyWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.category_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_id
     *
     * @return the value of t_blog.blog_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_id
     *
     * @param blogId the value for t_blog.blog_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.title
     *
     * @return the value of t_blog.title
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.title
     *
     * @param title the value for t_blog.title
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.create_time
     *
     * @return the value of t_blog.create_time
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.create_time
     *
     * @param createTime the value for t_blog.create_time
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.create_by
     *
     * @return the value of t_blog.create_by
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.create_by
     *
     * @param createBy the value for t_blog.create_by
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.dele_flag
     *
     * @return the value of t_blog.dele_flag
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getDeleFlag() {
        return deleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.dele_flag
     *
     * @param deleFlag the value for t_blog.dele_flag
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setDeleFlag(Integer deleFlag) {
        this.deleFlag = deleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.update_time
     *
     * @return the value of t_blog.update_time
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.update_time
     *
     * @param updateTime the value for t_blog.update_time
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.update_by
     *
     * @return the value of t_blog.update_by
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.update_by
     *
     * @param updateBy the value for t_blog.update_by
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.data_id
     *
     * @return the value of t_blog.data_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.data_id
     *
     * @param dataId the value for t_blog.data_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_desc
     *
     * @return the value of t_blog.blog_desc
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public String getBlogDesc() {
        return blogDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_desc
     *
     * @param blogDesc the value for t_blog.blog_desc
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setBlogDesc(String blogDesc) {
        this.blogDesc = blogDesc == null ? null : blogDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.key_words
     *
     * @return the value of t_blog.key_words
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public String getKeyWords() {
        return keyWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.key_words
     *
     * @param keyWords the value for t_blog.key_words
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setKeyWords(String keyWords) {
        this.keyWords = keyWords == null ? null : keyWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.category_id
     *
     * @return the value of t_blog.category_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.category_id
     *
     * @param categoryId the value for t_blog.category_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}