package com.zking.entity;

public class BlogCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.category_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.category_name
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.p_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.dele_flag
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer deleFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.category_id
     *
     * @return the value of t_blog_category.category_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.category_id
     *
     * @param categoryId the value for t_blog_category.category_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.category_name
     *
     * @return the value of t_blog_category.category_name
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.category_name
     *
     * @param categoryName the value for t_blog_category.category_name
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.p_id
     *
     * @return the value of t_blog_category.p_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.p_id
     *
     * @param pId the value for t_blog_category.p_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.dele_flag
     *
     * @return the value of t_blog_category.dele_flag
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getDeleFlag() {
        return deleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.dele_flag
     *
     * @param deleFlag the value for t_blog_category.dele_flag
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setDeleFlag(Integer deleFlag) {
        this.deleFlag = deleFlag;
    }
}