package com.zking.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_name
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.p_rid
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer pRid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.dele_flag
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    private Integer deleFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_id
     *
     * @return the value of t_role.role_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_id
     *
     * @param roleId the value for t_role.role_id
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_name
     *
     * @return the value of t_role.role_name
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_name
     *
     * @param roleName the value for t_role.role_name
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.p_rid
     *
     * @return the value of t_role.p_rid
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getpRid() {
        return pRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.p_rid
     *
     * @param pRid the value for t_role.p_rid
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setpRid(Integer pRid) {
        this.pRid = pRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.dele_flag
     *
     * @return the value of t_role.dele_flag
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public Integer getDeleFlag() {
        return deleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.dele_flag
     *
     * @param deleFlag the value for t_role.dele_flag
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    public void setDeleFlag(Integer deleFlag) {
        this.deleFlag = deleFlag;
    }
}