package com.zking.dao;

import com.zking.entity.BlogData;
import com.zking.entity.BlogDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    long countByExample(BlogDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int deleteByExample(BlogDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int deleteByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int insert(BlogData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int insertSelective(BlogData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    List<BlogData> selectByExampleWithBLOBs(BlogDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    List<BlogData> selectByExample(BlogDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    BlogData selectByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") BlogData record, @Param("example") BlogDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") BlogData record, @Param("example") BlogDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int updateByExample(@Param("record") BlogData record, @Param("example") BlogDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int updateByPrimaryKeySelective(BlogData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(BlogData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_data
     *
     * @mbg.generated Fri Jul 28 19:44:21 CST 2017
     */
    int updateByPrimaryKey(BlogData record);
}